Repository AY2324S1-CS2103T-T13-2/tp, pull requests merged in 2023-11, with the labels that each got.

#137 Update UG table of contents and spacing
  docs/UserGuide.md
Labels: type.Chore, type.Bug, priority.Low

#135 Update user guide for notification system
  .gitignore
  docs/UserGuide.md
  docs/images/birthdayNotification.png
Labels: type.Chore

#158 Fix image render issue and update UserGuide.md ToC
  docs/UserGuide.md
  docs/images/Final_Ui.png
Labels: type.Bug

#155 Add update photo feature to Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/updatephoto-command/UpdatePhotoCommandSequenceDiagram.puml
Labels: priority.High

#152 Update User Guide for `updatephoto` command
  docs/UserGuide.md
  docs/images/photopath.png
Labels: priority.High

#200 Fix inaccurate birthday notification behaviour
  src/main/java/seedu/address/model/event/EventFactory.java
Labels: priority.Medium

#215 Update PPP
  docs/team/vn-hao.md
Labels: type.Chore

#235 Add planned enhancement for corrupt addressbook.json, move planned enhancements to DG
  docs/DeveloperGuide.md
Labels: type.Bug
