Repository AY2324S1-CS2103T-T13-2/tp, pull requests merged in 2023-10, with the labels that each got.

#12 Update AboutUs.md
  docs/AboutUs.md
  docs/images/conradsoon.png
  docs/images/kokrui.png
  docs/images/limjunxian1.png
  docs/images/lordidiot.png
  docs/images/vn-hao.png
Labels: type.Enhancement

#52 Add emergency tags feature
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Story, priority.Medium

#68 Add tests for addalt
  src/main/java/seedu/address/logic/commands/AddAltCommand.java
  src/main/java/seedu/address/logic/parser/AddAltCommandParser.java
  src/test/java/seedu/address/logic/commands/AddAltCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAltCommandParserTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Chore, priority.Medium

#106 Rename image file extensions
  docs/images/birthdayNotification.png
  docs/images/optOutNotification.png
Labels: type.Chore

#107 Fix markbind style issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug

#110 Fix `note` not updating UI bug
  src/main/java/seedu/address/logic/commands/AddAltCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/event/EventFactoryTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: severity.Low

#111 Fix outdated docs
  docs/_markbind/layouts/default.md
  docs/index.md
Labels: type.Chore, type.Bug, severity.Low

#112 CLI for notes feature, rename `note` command to `addnote`
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/ViewNotesCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewNotesCommandParser.java
  src/main/java/seedu/address/ui/NotesWindow.java
  src/main/resources/view/NotesWindow.fxml
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewNotesCommandLogicTest.java
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewNotesCommandParserTest.java
  src/test/java/seedu/address/ui/NotesWindowTest.java
  src/test/java/seedu/address/ui/ViewNotesCommandUiTest.java
Labels: priority.Medium

#121 Fix variable names in test from `you_owe` to `youOwe`
  src/test/java/seedu/address/logic/parser/FindExpressionParserTest.java
Labels: type.Chore
